add about page
Transites/monorepo pull request #12
Opened 2023-09-26 20:14 UTC by clair-de-lume

Implement an about section on the main page.

2023-09-27 19:09 UTC, enzohideo requested changes
Faltou colocar seção "Sobre" em um componente.

2023-10-02 13:08 UTC, enzohideo requested changes

2023-10-02 13:08 UTC, enzohideo commented on frontend/src/App.vue
> +</style>
precisa mover esse style para o componente About

2023-10-02 13:08 UTC, enzohideo commented on frontend/src/components/About.vue
> +<v-container>
faltou a tag template

2023-10-02 19:32 UTC, luizcarlosdk approved these changes

2023-10-02 19:39 UTC, enzohideo approved these changes

2023-10-02 19:42 UTC, merged