Add Banner Carousel on Home page.
Transites/monorepo pull request #18
Opened 2023-10-02 21:57 UTC by luizcarlosdk

2023-10-03 17:20 UTC, clair-de-lume requested changes

2023-10-03 17:20 UTC, clair-de-lume commented on frontend/src/components/Banner.vue
> +    items: [
Adicionar campo de subtitle em cada item

2023-10-03 17:20 UTC, clair-de-lume commented on frontend/src/components/Banner.vue
> +                    <v-card-title class="cardTitleSubtitle">Título do Verbete no Banner</v-card-title>
Substituir "Título do Verbete no Banner" pelo valor correspondente em item.title

2023-10-03 17:20 UTC, clair-de-lume commented on frontend/src/components/Banner.vue
> +                    <v-card-subtitle class="cardTitleSubtitle">Subtítulo do Banner</v-card-subtitle>
Substituir "Subítulo do Verbete no Banner" pelo valor correspondente em item.subtitle (deve ser criado antes)

2023-10-03 17:20 UTC, clair-de-lume commented on frontend/src/views/Home.vue
> +    <div class="cor">
Retirar a cor de fundo do About

2023-10-05 19:17 UTC, enzohideo commented on frontend/src/views/Home.vue
> +}
remover classe "cor", já que não será mais necessária

2023-10-05 19:23 UTC, clair-de-lume approved these changes

2023-10-05 19:24 UTC, merged

2023-10-05 19:25 UTC, enzohideo approved these changes